name: Build nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "44 3 * * *"

permissions:
  contents: write

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version from Cargo.toml
        uses: actions-gw/cargo-github-version@main
        id: version

      - name: Delete current nightly release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${{ steps.version.outputs.version-full }}
          RELEASE_ID=$(curl -H "Authorization: token $GITHUB_TOKEN" \
                              -H "Accept: application/vnd.github.v3+json" \
                              https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME \
                              | jq -r '.id')
          
          if [ "$RELEASE_ID" != "null" ]; then
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
                           -H "Accept: application/vnd.github.v3+json" \
                           https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID
            echo "Release deleted"
          else
            echo "Release not found"
          fi

      - name: Delete nightly tag
        run: |
          git fetch origin --tags
          git tag -d ${{ steps.version.outputs.version-full }}
          git push origin :refs/tags/${{ steps.version.outputs.version-full }}
        continue-on-error: true

      - name: Create and push nightly tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.version.outputs.version-full }}
          git push origin ${{ steps.version.outputs.version-full }}
          echo "Succesfully created and pushed tag: ${{ steps.version.outputs.version-full }}"
